# Generated by Django 4.0.5 on 2022-07-01 22:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocName', models.CharField(max_length=64, verbose_name='Место Работы')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64, verbose_name='Имя')),
                ('Spec', models.CharField(max_length=64, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start', models.TimeField(verbose_name='Начало Работы')),
                ('end', models.TimeField(verbose_name='Конец Работы')),
                ('idSpec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.worker', verbose_name='Специалист')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=32, verbose_name='Имя')),
                ('Cphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер')),
                ('Order', models.CharField(max_length=64, verbose_name='Цель')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start', models.TimeField(verbose_name='Начало Работы')),
                ('end', models.TimeField(verbose_name='Конец Работы')),
                ('Loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.location', verbose_name='Место')),
                ('Spec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.worker', verbose_name='Специалист')),
            ],
        ),
    ]
